### ISSUE TITLE
signature different from /load-collada-dae/expand-verticies ?

### ISSUE THREAD

**Issue by kevzettler** [chinedufn/expand-vertex-data#1]
Just tried dropping this into skeletal-animation-system and hitting an error

I previously had:

`const expandVertices = require('load-collada-dae/src/expand-vertices.js')`

changed to 
`const expandVertices = require('expand-vertex-data')`

Invoking like:
`var vertexData = expandVertices(cowboy, {hasTexture: true})`

Now seeing an error: 
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at setVertexData (http://localhost:9966/regl.js:602:33)
    at http://localhost:9966/regl.js:573:7
    at Array.forEach (native)
    at expandVertexData (http://localhost:9966/regl.js:565:46)
    at Object.3../asset/cowboy.json (http://localhost:9966/regl.js:126:18)
    at s (http://localhost:9966/regl.js:1:254)
    at e (http://localhost:9966/regl.js:1:425)
    at http://localhost:9966/regl.js:1:443
```

Looks like maybe from:
https://github.com/chinedufn/expand-vertex-data/blob/master/src/expand-vertex-data.js#L53-L58

**Comment by chinedufn** [comment]
Ah this line is supposed to say `jointsAndWeights` not `compressedData.jointsAndWeights. I can fix that after work tomorrow, or if you have a sec mind fixing and I'll accept the PR?

This is what happens when I try to skip over writing real tests 🙄

**Comment by chinedufn** [comment]
Fixed
